import { Theme } from './types';

export const themes: Theme[] = [
  {
    id: 'deep-ruby',
    name: 'Глубокий рубин',
    subtitle: 'PT Serif/Inter',
    colors: {
      primary: '#740606',
      secondary: '#D4A574',
      background: '#740606',
      text: '#FFFFFF',
      accent: '#D4A574',
    },
    cardColors: {
      leftPanel: '#740606',
      rightTop: '#a52a2a',
      rightBottom: '#8b0000',
      titleColor: '#FFFFFF',
      bodyColor: '#FFFFFF',
    },
    fontFamily: 'PT Serif, serif',
  },
  {
    id: 'retro-modern',
    name: 'Ретро модерн',
    subtitle: 'Inter',
    colors: {
      primary: '#8B5E3C',
      secondary: '#FFFE44',
      background: '#8B5E3C',
      text: '#FFFE44',
      accent: '#FFFE44',
    },
    cardColors: {
      leftPanel: '#8B5E3C',
      rightTop: '#FFFE44',
      rightBottom: '#C4592A',
      titleColor: '#FFFE44',
      bodyColor: 'rgba(255,254,68,0.64)',
    },
    fontFamily: 'Inter, sans-serif',
  },
  {
    id: 'neo-minimalism',
    name: 'Нео минимализм',
    subtitle: 'Inter',
    colors: {
      primary: '#FFFFFF',
      secondary: '#F5F5F5',
      background: '#FFFFFF',
      text: '#11192C',
      accent: '#666666',
    },
    cardColors: {
      leftPanel: '#FFFFFF',
      rightTop: '#F5F5F5',
      rightBottom: '#E8E8E8',
      titleColor: '#11192C',
      bodyColor: 'rgba(17,25,44,0.64)',
    },
    fontFamily: 'Inter, sans-serif',
  },
  {
    id: 'japanese-style',
    name: 'Японский стиль',
    subtitle: 'Inter',
    colors: {
      primary: '#5C6B4E',
      secondary: '#C5A882',
      background: '#5C6B4E',
      text: '#FFFFFF',
      accent: '#C5A882',
    },
    cardColors: {
      leftPanel: '#5C6B4E',
      rightTop: '#8B9D77',
      rightBottom: '#3D4A33',
      titleColor: '#FFFFFF',
      bodyColor: 'rgba(255,255,255,0.64)',
    },
    fontFamily: 'Inter, sans-serif',
  },
  {
    id: 'dark-graphite',
    name: 'Тёмный графит',
    subtitle: 'Montserrat',
    colors: {
      primary: '#0C343D',
      secondary: '#4A90D9',
      background: '#0C343D',
      text: '#FFFFFF',
      accent: '#4A90D9',
    },
    cardColors: {
      leftPanel: '#0C343D',
      rightTop: '#1A5A6B',
      rightBottom: '#062028',
      titleColor: '#FFFFFF',
      bodyColor: 'rgba(255,255,255,0.64)',
    },
    fontFamily: 'Montserrat, sans-serif',
  },
  {
    id: 'dark-style',
    name: 'Тёмный стиль',
    subtitle: 'Inter',
    colors: {
      primary: '#181818',
      secondary: '#333333',
      background: '#181818',
      text: '#FFFFFF',
      accent: '#888888',
    },
    cardColors: {
      leftPanel: '#181818',
      rightTop: '#333333',
      rightBottom: '#0A0A0A',
      titleColor: '#FFFFFF',
      bodyColor: 'rgba(255,255,255,0.64)',
    },
    fontFamily: 'Inter, sans-serif',
  },
  {
    id: 'scandinavian',
    name: 'Скандинавская',
    subtitle: 'Roboto',
    colors: {
      primary: '#FFFDE6',
      secondary: '#B8A88A',
      background: '#FFFDE6',
      text: '#233939',
      accent: '#6B8E7B',
    },
    cardColors: {
      leftPanel: '#FFFDE6',
      rightTop: '#E8E0C8',
      rightBottom: '#D4C9A8',
      titleColor: '#233939',
      bodyColor: 'rgba(35,57,57,0.64)',
    },
    fontFamily: 'Roboto, sans-serif',
  },
  {
    id: 'pine-evening',
    name: 'Хвойный вечер',
    subtitle: 'Arial/Inter',
    colors: {
      primary: '#123332',
      secondary: '#4A6B4E',
      background: '#123332',
      text: '#FFFFFF',
      accent: '#8FBC8F',
    },
    cardColors: {
      leftPanel: '#123332',
      rightTop: '#2A5A4A',
      rightBottom: '#0A1A1A',
      titleColor: '#FFFFFF',
      bodyColor: 'rgba(255,255,255,0.64)',
    },
    fontFamily: 'Arial, Inter, sans-serif',
  },
];
